### ISSUE TITLE
Heavy project - Need a lighter branch

### ISSUE THREAD

**Issue by mr-cozay** [cometchat-pro-samples/ionic-chat-app#1]
The project is too heavy, can you create a lighter branch? a branch without this folders: *nodes_modules
*platforms
*resources
*plugins;
because these folders are generated automatically in a project and these are different depending on the operating system. This approach will facilitate cloning and forking ... Thanks in advance.
Great job, very useful API.

**Comment by ranjanravi85** [comment]
Hello @mr-cozay ,

We have made it lighter,you can use the same.
