### ISSUE TITLE
Issue in Compile or Build

### ISSUE THREAD

**Issue by robelsust** [cometchat-pro-samples/ionic-chat-app#5]
Code editor shows error, also when try to compile error is thrown

 CometChat.addCallListener(
    listnerID,
    new CometChat.CallListener({
     onIncomingCallReceived(call) {
      console.log("Incoming call:", call);
      var sid = call.sessionId;

      CometChat.acceptCall(sid).then(
        call => {
         console.log("Call accepted successfully:", call);

         CometChat.startCall(
          sid,
          this.callScreen,
          new CometChat.OngoingCallListener({
           onUserJoined: user => {
            /* Notification received here if another user joins the call. */
            console.log("User joined call:", user);
            /* this method can be use to display message or perform any actions if someone joining the call */
           },
           onUserLeft: user => {
            /* Notification received here if another user left the call. */
            console.log("User left call:", user);
            /* this method can be use to display message or perform any actions if someone leaving the call */
           },
           onCallEnded: call => {
            /* Notification received here if current ongoing call is ended. */
            console.log("Call ended:", call);
            /* hiding/closing the call screen can be done here. */
           }
          })
         );         
         // start the call using the startCall() method
        },
        error => {
         console.log("Call acceptance failed with error", error);
         // handle exception
        }
       );

      // Handle incoming call
     },
     onOutgoingCallAccepted(call) {
      console.log("Outgoing call accepted:", call);
      // Outgoing Call Accepted
     },
     onOutgoingCallRejected(call) {
      console.log("Outgoing call rejected:", call);
      // Outgoing Call Rejected
     },
     onIncomingCallCancelled(call) {
      console.log("Incoming call calcelled:", call);
     }
    })
   );

ERROR in src/app/home/home.page.ts:84:32 - error TS2345: Argument of type '{ onIncomingCallReceived(call: any): void; onOutgoingCallAccepted(call: any): void; onOutgoingCallRejected(call: any): void; onIncomingCallCancelled(call: any): void; }' is not assignable to parameter of type 'string'.

 84     new CometChat.CallListener({
                                   ~
 85      onIncomingCallReceived(call) {
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
134      }
    ~~~~~~
135     })
    ~~~~~
src/app/home/home.page.ts:96:25 - error TS2339: Property 'OngoingCallListener' does not exist on type 'typeof CometChat'.

96           new CometChat.OngoingCallListener({
                           ~~~~~~~~~~~~~~~~~~~

[ERROR] An error occurred while running subprocess ng.
        
        ng run app:ionic-cordova-build --platform=ios exited with exit code 1.

**Comment by mayur-bhandari** [comment]
Hello @robelsust, we currently do not support audio/video calling for ionic. We will let you know once this feature is live.

**Comment by mayur-bhandari** [comment]
Hello @robelsust , we are looking into this and will get back to you.

**Comment by mayur-bhandari** [comment]
Hello @robelsust, I tried compiling the source code and it did compile properly. I think you are trying to integrate calling in ionic 4. But currently we do not provide video/voice calling for ionic as of now. We will let you know when this feature goes live. Thank you for reporting.
