### ISSUE TITLE
Gradle sync error

### ISSUE THREAD

**Issue by msp-ampcome** [cometchat-pro-samples/ionic-chat-app#7]
### I am trying to build the sample calling app in android, but gradle sync is throwing errors like

> Unable to resolve dependency for ':cometchat-pro-ionic-calls@debugAndroidTest/compileClasspath': Could not resolve com.cometchat:pro-android-calls-sdk:1.0.7.
> Unable to resolve dependency for ':cometchat-pro-ionic-calls@debug/compileClasspath': Could not resolve com.cometchat:pro-android-calls-sdk:1.0.7.
> Unable to resolve dependency for ':cometchat-pro-ionic-calls@debugUnitTest/compileClasspath': Could not resolve com.cometchat:pro-android-calls-sdk:1.0.7.

We were trying integrate calling in our app, This issue happened there also, so We thought maybe we messed up the setup and tried to build the sample app. but here also, we are facing the same issue.

> but in our app the dependency version was com.cometchat:pro-android-calls-sdk:2.0.2-beta1.

![image](https://user-images.githubusercontent.com/83330300/117101559-1b512580-ad94-11eb-8289-7dae37b9d5d5.png)

Please provide a solution for us, We really like to use Cometchat to build our video conferencing solution. Thank you

**Comment by mayur-bhandari** [comment]
Hello @msp-ampcome,

Please update the Chat & Calling SDK to the latest version. The latest version of CometChat Cordova Ionic SDK(@cometchat-pro/cordova-ionic-chat) is v2.3.1 & the latest version of CometChat Ionic Calls(@cometchat-pro/ionic-calls) is v2.0.2.

Also, you need to update the maven URL in the project level build gradle file from `"https://dl.bintray.com/cometchat/pro"` to  `"https://dl.cloudsmith.io/public/cometchat/cometchat-pro-android/maven/"`
